apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::001668499019:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-90MRMPW9HQ1G
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn : arn:aws:iam::001668499019:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-14T23:38:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1508"
  uid: 4fcb2972-cfc3-493c-913f-315e700f27d2
